//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class ConfigBD : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigBD defaultInstance = ((ConfigBD)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigBD())));
        
        public static ConfigBD Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=D:\\JUAN DIEGO\\Google Drive\\Proyectos\\SYSConfac\\Base de datos\\SISAguaB" +
            "D.db")]
        public string ConnectionDefault {
            get {
                return ((string)(this["ConnectionDefault"]));
            }
            set {
                this["ConnectionDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLITE")]
        public string MotorBD {
            get {
                return ((string)(this["MotorBD"]));
            }
            set {
                this["MotorBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MANUAL")]
        public string TipoBackup {
            get {
                return ((string)(this["TipoBackup"]));
            }
            set {
                this["TipoBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Frecuencia {
            get {
                return ((int)(this["Frecuencia"]));
            }
            set {
                this["Frecuencia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\JUAN DIEGO\\Google Drive\\Proyectos\\SYSConfac\\Base de datos\\Backups")]
        public string RutaDestinoBackup {
            get {
                return ((string)(this["RutaDestinoBackup"]));
            }
            set {
                this["RutaDestinoBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Data Source=E:\Juan Diego\Google Drive\Proyectos\SYSConfac\Base de datos\SYSConfacBDPrueba - copia</string>
  <string>D:\JUAN DIEGO\Google Drive\Proyectos\SYSConfac\Base de datos\SYSConfacBDPrueba - copia</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConnectionsStrings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConnectionsStrings"]));
            }
            set {
                this["ConnectionsStrings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\JUAN DIEGO\\Google Drive\\Proyectos\\SYSConfac\\Base de datos\\SISAguaBD.db")]
        public string FileNameConnection {
            get {
                return ((string)(this["FileNameConnection"]));
            }
            set {
                this["FileNameConnection"] = value;
            }
        }
    }
}
