//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionAdministracion.Formularios.FormsConfiguraciones.FormsConfiguraciones {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class ConfigFacturas : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigFacturas defaultInstance = ((ConfigFacturas)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigFacturas())));
        
        public static ConfigFacturas Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Titulo_reporte {
            get {
                return ((string)(this["Titulo_reporte"]));
            }
            set {
                this["Titulo_reporte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Medida_default {
            get {
                return ((string)(this["Medida_default"]));
            }
            set {
                this["Medida_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Ancho {
            get {
                return ((decimal)(this["Ancho"]));
            }
            set {
                this["Ancho"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Alto {
            get {
                return ((decimal)(this["Alto"]));
            }
            set {
                this["Alto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MargenAbajo {
            get {
                return ((decimal)(this["MargenAbajo"]));
            }
            set {
                this["MargenAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MargenArriba {
            get {
                return ((decimal)(this["MargenArriba"]));
            }
            set {
                this["MargenArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MargenDerecha {
            get {
                return ((decimal)(this["MargenDerecha"]));
            }
            set {
                this["MargenDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MargenIzquierda {
            get {
                return ((decimal)(this["MargenIzquierda"]));
            }
            set {
                this["MargenIzquierda"] = value;
            }
        }
    }
}
