//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionAdministracion.Formularios.FormsConfiguraciones.FormsConfiguraciones {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class ConfigGeneral : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigGeneral defaultInstance = ((ConfigGeneral)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigGeneral())));
        
        public static ConfigGeneral Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Nombre_empresa {
            get {
                return ((string)(this["Nombre_empresa"]));
            }
            set {
                this["Nombre_empresa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Nombre_presidente {
            get {
                return ((string)(this["Nombre_presidente"]));
            }
            set {
                this["Nombre_presidente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Ruta_archivos {
            get {
                return ((string)(this["Ruta_archivos"]));
            }
            set {
                this["Ruta_archivos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Id_caja_principal {
            get {
                return ((int)(this["Id_caja_principal"]));
            }
            set {
                this["Id_caja_principal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Meses_alerta_corte {
            get {
                return ((int)(this["Meses_alerta_corte"]));
            }
            set {
                this["Meses_alerta_corte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Meses_corte {
            get {
                return ((int)(this["Meses_corte"]));
            }
            set {
                this["Meses_corte"] = value;
            }
        }
    }
}
