//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionAdministracion.Formularios.FormsConfiguraciones.FormsConfiguraciones {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class ConfigTarifas : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigTarifas defaultInstance = ((ConfigTarifas)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigTarifas())));
        
        public static ConfigTarifas Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Id_tarifa_lectura {
            get {
                return ((int)(this["Id_tarifa_lectura"]));
            }
            set {
                this["Id_tarifa_lectura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Id_tarifa_sesion {
            get {
                return ((int)(this["Id_tarifa_sesion"]));
            }
            set {
                this["Id_tarifa_sesion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Id_tarifa_manual {
            get {
                return ((int)(this["Id_tarifa_manual"]));
            }
            set {
                this["Id_tarifa_manual"] = value;
            }
        }
    }
}
